### ISSUE TITLE
how did you label data?

### ISSUE THREAD

**Issue by bingyulab** [wenet-e2e/opencpop#9]
Which tool did you use to label data? I cann't find in paper or other document. 
Is it Logic Pro + praat? or something else.

**Comment by zpcoftts** [comment]
> Which tool did you use to label data? I cann't find in paper or other document. Is it Logic Pro + praat? or something else.

yes, logic + praat, with our prelabeling services.  
At the same time, we have developed a web-side annotation system. This system will provide services to the outside world when the time is right.

**Comment by bingyulab** [comment]
Thank you very much.
